package fopnetbeans;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shawn
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    DefaultTableModel model;
    
    Color mouseEnterColor = new Color(61,72,73);
    Color mouseExitColor = new Color(12,12,12);
    
    public HomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        if (SelectionMenu._default) {
            StartDateText.setText("Throughout the File");
            EndDateText.setText("Throughout the File");
        }
        else {
            StartDateText.setText(PromptDate.startdate);
            EndDateText.setText(PromptDate.enddate);
        }
        
        CharactersText.setText(Integer.toString(FileProperties.CharacterCount));
        WordsText.setText(Integer.toString(FileProperties.WordCount));
        LinesText.setText(Integer.toString(FileProperties.LineCount));
        PeriodText.setText(Double.toString(FileProperties.d) + " day(s) " + Double.toString(FileProperties.h) + " hour(s) " + Double.toString(FileProperties.m) + " minute(s) " + Double.toString(FileProperties.s) + " second(s) ");
        UserText.setText(Integer.toString(FileProperties.copy.size()));
        PartitionsText.setText(Integer.toString(FileProperties.filtered_partition.size()));
        FileSizeText.setText(String.format("%,d bytes", FileProperties.bytes) + " / " + String.format("%,d kilobytes %n", FileProperties.bytes / 1024));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        JobCountPanel = new javax.swing.JPanel();
        JobCountText = new javax.swing.JLabel();
        HomePagePanel = new javax.swing.JPanel();
        HomePageText = new javax.swing.JLabel();
        PartitionPanel = new javax.swing.JPanel();
        PartitionText = new javax.swing.JLabel();
        ErrorsPanel = new javax.swing.JPanel();
        ErrorsText = new javax.swing.JLabel();
        TimePanel = new javax.swing.JPanel();
        TimeText = new javax.swing.JLabel();
        InitPrioPanel = new javax.swing.JPanel();
        InitPrioText = new javax.swing.JLabel();
        KillRequestPanel = new javax.swing.JPanel();
        KillRequestText = new javax.swing.JLabel();
        DailyReportPanel = new javax.swing.JPanel();
        DailyReportText = new javax.swing.JLabel();
        MonthlyReportPanel = new javax.swing.JPanel();
        MonthlyReportText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        StartDateText = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        EndDateText = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        CharactersText = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        WordsText = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        LinesText = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        PeriodText = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        UserText = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        PartitionsText = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        FileSizeText = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dashboard");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        jPanel2.setBackground(new java.awt.Color(12, 12, 12));
        jPanel2.setPreferredSize(new java.awt.Dimension(226, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 3));

        JobCountPanel.setBackground(new java.awt.Color(12, 12, 12));

        JobCountText.setBackground(new java.awt.Color(51, 51, 51));
        JobCountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JobCountText.setForeground(new java.awt.Color(255, 255, 255));
        JobCountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobCountText.setText("Job Count");
        JobCountText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobCountTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobCountTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobCountTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JobCountPanelLayout = new javax.swing.GroupLayout(JobCountPanel);
        JobCountPanel.setLayout(JobCountPanelLayout);
        JobCountPanelLayout.setHorizontalGroup(
            JobCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JobCountPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JobCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JobCountPanelLayout.setVerticalGroup(
            JobCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobCountPanelLayout.createSequentialGroup()
                .addComponent(JobCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(JobCountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        HomePagePanel.setBackground(new java.awt.Color(102, 102, 255));

        HomePageText.setBackground(new java.awt.Color(51, 51, 51));
        HomePageText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HomePageText.setForeground(new java.awt.Color(255, 255, 255));
        HomePageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomePageText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_24px.png"))); // NOI18N
        HomePageText.setText("Home Page");

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(HomePagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        PartitionPanel.setBackground(new java.awt.Color(12, 12, 12));

        PartitionText.setBackground(new java.awt.Color(51, 51, 51));
        PartitionText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PartitionText.setForeground(new java.awt.Color(255, 255, 255));
        PartitionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PartitionText.setText("Number of Jobs by Partitions");
        PartitionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PartitionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PartitionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PartitionTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PartitionPanelLayout = new javax.swing.GroupLayout(PartitionPanel);
        PartitionPanel.setLayout(PartitionPanelLayout);
        PartitionPanelLayout.setHorizontalGroup(
            PartitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PartitionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PartitionText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PartitionPanelLayout.setVerticalGroup(
            PartitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartitionPanelLayout.createSequentialGroup()
                .addComponent(PartitionText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(PartitionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, -1));

        ErrorsPanel.setBackground(new java.awt.Color(12, 12, 12));

        ErrorsText.setBackground(new java.awt.Color(51, 51, 51));
        ErrorsText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ErrorsText.setForeground(new java.awt.Color(255, 255, 255));
        ErrorsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorsText.setText("Number of Errors");
        ErrorsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ErrorsPanelLayout = new javax.swing.GroupLayout(ErrorsPanel);
        ErrorsPanel.setLayout(ErrorsPanelLayout);
        ErrorsPanelLayout.setHorizontalGroup(
            ErrorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErrorsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ErrorsText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ErrorsPanelLayout.setVerticalGroup(
            ErrorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorsPanelLayout.createSequentialGroup()
                .addComponent(ErrorsText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(ErrorsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        TimePanel.setBackground(new java.awt.Color(12, 12, 12));

        TimeText.setBackground(new java.awt.Color(51, 51, 51));
        TimeText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TimeText.setForeground(new java.awt.Color(255, 255, 255));
        TimeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeText.setText("Average Job Execution Time");
        TimeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TimeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TimeTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(TimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, -1));

        InitPrioPanel.setBackground(new java.awt.Color(12, 12, 12));

        InitPrioText.setBackground(new java.awt.Color(51, 51, 51));
        InitPrioText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InitPrioText.setForeground(new java.awt.Color(255, 255, 255));
        InitPrioText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InitPrioText.setText("Initial Priority Distribution");
        InitPrioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout InitPrioPanelLayout = new javax.swing.GroupLayout(InitPrioPanel);
        InitPrioPanel.setLayout(InitPrioPanelLayout);
        InitPrioPanelLayout.setHorizontalGroup(
            InitPrioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InitPrioPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(InitPrioText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        InitPrioPanelLayout.setVerticalGroup(
            InitPrioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitPrioPanelLayout.createSequentialGroup()
                .addComponent(InitPrioText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(InitPrioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, -1));

        KillRequestPanel.setBackground(new java.awt.Color(12, 12, 12));

        KillRequestText.setBackground(new java.awt.Color(51, 51, 51));
        KillRequestText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        KillRequestText.setForeground(new java.awt.Color(255, 255, 255));
        KillRequestText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KillRequestText.setText("Number of Kill Request by User");
        KillRequestText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout KillRequestPanelLayout = new javax.swing.GroupLayout(KillRequestPanel);
        KillRequestPanel.setLayout(KillRequestPanelLayout);
        KillRequestPanelLayout.setHorizontalGroup(
            KillRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KillRequestPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(KillRequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        KillRequestPanelLayout.setVerticalGroup(
            KillRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KillRequestPanelLayout.createSequentialGroup()
                .addComponent(KillRequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(KillRequestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, -1));

        DailyReportPanel.setBackground(new java.awt.Color(12, 12, 12));

        DailyReportText.setBackground(new java.awt.Color(51, 51, 51));
        DailyReportText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DailyReportText.setForeground(new java.awt.Color(255, 255, 255));
        DailyReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DailyReportText.setText("Daily Report");
        DailyReportText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DailyReportPanelLayout = new javax.swing.GroupLayout(DailyReportPanel);
        DailyReportPanel.setLayout(DailyReportPanelLayout);
        DailyReportPanelLayout.setHorizontalGroup(
            DailyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DailyReportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DailyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DailyReportPanelLayout.setVerticalGroup(
            DailyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DailyReportPanelLayout.createSequentialGroup()
                .addComponent(DailyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(DailyReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, -1));

        MonthlyReportPanel.setBackground(new java.awt.Color(12, 12, 12));

        MonthlyReportText.setBackground(new java.awt.Color(51, 51, 51));
        MonthlyReportText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        MonthlyReportText.setForeground(new java.awt.Color(255, 255, 255));
        MonthlyReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthlyReportText.setText("Monthly Report");
        MonthlyReportText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MonthlyReportPanelLayout = new javax.swing.GroupLayout(MonthlyReportPanel);
        MonthlyReportPanel.setLayout(MonthlyReportPanelLayout);
        MonthlyReportPanelLayout.setHorizontalGroup(
            MonthlyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonthlyReportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MonthlyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MonthlyReportPanelLayout.setVerticalGroup(
            MonthlyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonthlyReportPanelLayout.createSequentialGroup()
                .addComponent(MonthlyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(MonthlyReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(12, 12, 12));
        jLabel10.setText("File Properties:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 50));

        jPanel3.setBackground(new java.awt.Color(12, 12, 12));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        StartDateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StartDateText.setForeground(new java.awt.Color(255, 255, 255));
        StartDateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StartDateText.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 60));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 12, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Start Date:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(12, 12, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("End Date:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 200, 30));

        jPanel5.setBackground(new java.awt.Color(12, 12, 12));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        EndDateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EndDateText.setForeground(new java.awt.Color(255, 255, 255));
        EndDateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EndDateText.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EndDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EndDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 200, 60));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(12, 12, 12));
        jLabel14.setText("Welcome, User");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 170, 50));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 12, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Number of Characters");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 30));

        jPanel7.setBackground(new java.awt.Color(12, 12, 12));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        CharactersText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CharactersText.setForeground(new java.awt.Color(255, 255, 255));
        CharactersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CharactersText.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CharactersText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CharactersText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(12, 12, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Number of Words");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 200, 30));

        jPanel9.setBackground(new java.awt.Color(12, 12, 12));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        WordsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        WordsText.setForeground(new java.awt.Color(255, 255, 255));
        WordsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WordsText.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WordsText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WordsText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 200, 60));

        jPanel10.setBackground(new java.awt.Color(12, 12, 12));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        LinesText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LinesText.setForeground(new java.awt.Color(255, 255, 255));
        LinesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LinesText.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LinesText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LinesText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 200, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(12, 12, 12));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Number of Lines");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 200, 30));

        jPanel11.setBackground(new java.awt.Color(12, 12, 12));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        PeriodText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PeriodText.setForeground(new java.awt.Color(255, 255, 255));
        PeriodText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PeriodText.setText("0");

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(12, 12, 12));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Start Date:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeriodText, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeriodText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1080, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(12, 12, 12));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total Period for the Log File Given");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 1100, 30));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(12, 12, 12));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Number of Users");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 200, 30));

        jPanel12.setBackground(new java.awt.Color(12, 12, 12));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        UserText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserText.setForeground(new java.awt.Color(255, 255, 255));
        UserText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserText.setText("0");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(12, 12, 12));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Start Date:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 200, -1));

        jPanel13.setBackground(new java.awt.Color(12, 12, 12));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        PartitionsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PartitionsText.setForeground(new java.awt.Color(255, 255, 255));
        PartitionsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PartitionsText.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PartitionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PartitionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 200, 60));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(12, 12, 12));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Number of Partitions");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 200, 30));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(12, 12, 12));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("File Size");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 90, 30));

        jPanel14.setBackground(new java.awt.Color(12, 12, 12));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        FileSizeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FileSizeText.setForeground(new java.awt.Color(255, 255, 255));
        FileSizeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileSizeText.setText("0");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(12, 12, 12));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Start Date:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FileSizeText, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FileSizeText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 420, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JobCountTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobCountTextMouseEntered
        JobCountPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_JobCountTextMouseEntered

    private void JobCountTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobCountTextMouseExited
        JobCountPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_JobCountTextMouseExited

    private void PartitionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseEntered
        PartitionPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_PartitionTextMouseEntered

    private void PartitionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseExited
        PartitionPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_PartitionTextMouseExited

    private void TimeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseEntered
        TimePanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_TimeTextMouseEntered

    private void TimeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseExited
        TimePanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_TimeTextMouseExited

    private void InitPrioTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseEntered
        InitPrioPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_InitPrioTextMouseEntered

    private void InitPrioTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseExited
        InitPrioPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_InitPrioTextMouseExited

    private void DailyReportTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseEntered
        DailyReportPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_DailyReportTextMouseEntered

    private void DailyReportTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseExited
        DailyReportPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_DailyReportTextMouseExited

    private void MonthlyReportTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseEntered
        MonthlyReportPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_MonthlyReportTextMouseEntered

    private void MonthlyReportTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseExited
        MonthlyReportPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_MonthlyReportTextMouseExited

    private void JobCountTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobCountTextMouseClicked
        JobCountDashboard dashboard = new JobCountDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JobCountTextMouseClicked

    private void PartitionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseClicked
        PartitionDashboardPC dashboard = new PartitionDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PartitionTextMouseClicked

    private void TimeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseClicked
        AvgExecTimeDashboard dashboard;
        dashboard = new AvgExecTimeDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TimeTextMouseClicked

    private void InitPrioTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseClicked
        InitPrioDashboardPC dashboard = new InitPrioDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InitPrioTextMouseClicked

    private void DailyReportTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseClicked
        DailyReportPromptDate dashboard = new DailyReportPromptDate();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DailyReportTextMouseClicked

    private void MonthlyReportTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseClicked
        MonthlyReportDashboard dashboard = new MonthlyReportDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MonthlyReportTextMouseClicked

    private void KillRequestTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseClicked
        KillRequestDashboard dashboard = new KillRequestDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KillRequestTextMouseClicked

    private void KillRequestTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseEntered
        KillRequestPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_KillRequestTextMouseEntered

    private void KillRequestTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseExited
        KillRequestPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_KillRequestTextMouseExited

    private void ErrorsTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseClicked
        ErrorsDashboardPC dashboard = new ErrorsDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ErrorsTextMouseClicked

    private void ErrorsTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseEntered
        ErrorsPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_ErrorsTextMouseEntered

    private void ErrorsTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseExited
        ErrorsPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_ErrorsTextMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CharactersText;
    private javax.swing.JPanel DailyReportPanel;
    private javax.swing.JLabel DailyReportText;
    private javax.swing.JLabel EndDateText;
    private javax.swing.JPanel ErrorsPanel;
    private javax.swing.JLabel ErrorsText;
    private javax.swing.JLabel FileSizeText;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel HomePageText;
    private javax.swing.JPanel InitPrioPanel;
    private javax.swing.JLabel InitPrioText;
    private javax.swing.JPanel JobCountPanel;
    private javax.swing.JLabel JobCountText;
    private javax.swing.JPanel KillRequestPanel;
    private javax.swing.JLabel KillRequestText;
    private javax.swing.JLabel LinesText;
    private javax.swing.JPanel MonthlyReportPanel;
    private javax.swing.JLabel MonthlyReportText;
    private javax.swing.JPanel PartitionPanel;
    private javax.swing.JLabel PartitionText;
    private javax.swing.JLabel PartitionsText;
    private javax.swing.JLabel PeriodText;
    private javax.swing.JLabel StartDateText;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JLabel TimeText;
    private javax.swing.JLabel UserText;
    private javax.swing.JLabel WordsText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
