package fopnetbeans;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shawn
 */
public class JobCountDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    DefaultTableModel model;
    
    Color mouseEnterColor = new Color(61,72,73);
    Color mouseExitColor = new Color(12,12,12);
    
    public JobCountDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        SubmissionsText.setText(Integer.toString(SuccessRate.jobSubmissions));
        CompletionsText.setText(Integer.toString(SuccessRate.jobCompletions));
        SuccessfulText.setText(Integer.toString(SuccessRate.successfulJobs));
        SuccessfulRateText.setText(String.format("%.2f",(SuccessRate.successfulJobs / (float) SuccessRate.jobCompletions) * 100) + "%");
        SubmissionRateText.setText(String.format("%.2f", (float)(SuccessRate.jobSubmissions/SuccessRate.dayDifference)));
        CompletionRateText.setText(String.format("%.2f", SuccessRate.jobCompletions/(SuccessRate.dayDifference)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        JobCountPanel = new javax.swing.JPanel();
        JobCountText = new javax.swing.JLabel();
        HomePagePanel = new javax.swing.JPanel();
        HomePageText = new javax.swing.JLabel();
        PartitionPanel = new javax.swing.JPanel();
        PartitionText = new javax.swing.JLabel();
        ErrorsPanel = new javax.swing.JPanel();
        ErrorsText = new javax.swing.JLabel();
        TimePanel = new javax.swing.JPanel();
        TimeText = new javax.swing.JLabel();
        InitPrioPanel = new javax.swing.JPanel();
        InitPrioText = new javax.swing.JLabel();
        KillRequestPanel = new javax.swing.JPanel();
        KillRequestText = new javax.swing.JLabel();
        DailyReportPanel = new javax.swing.JPanel();
        DailyReportText = new javax.swing.JLabel();
        MonthlyReportPanel = new javax.swing.JPanel();
        MonthlyReportText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SubmissionsText = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        CompletionsText = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        SuccessfulText = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        SuccessfulRateText = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        SubmissionRateText = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        CompletionRateText = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dashboard");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        jPanel2.setBackground(new java.awt.Color(12, 12, 12));
        jPanel2.setPreferredSize(new java.awt.Dimension(226, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 3));

        JobCountPanel.setBackground(new java.awt.Color(102, 102, 255));

        JobCountText.setBackground(new java.awt.Color(102, 102, 255));
        JobCountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JobCountText.setForeground(new java.awt.Color(255, 255, 255));
        JobCountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobCountText.setText("Job Count");

        javax.swing.GroupLayout JobCountPanelLayout = new javax.swing.GroupLayout(JobCountPanel);
        JobCountPanel.setLayout(JobCountPanelLayout);
        JobCountPanelLayout.setHorizontalGroup(
            JobCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JobCountPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JobCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JobCountPanelLayout.setVerticalGroup(
            JobCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobCountPanelLayout.createSequentialGroup()
                .addComponent(JobCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(JobCountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        HomePagePanel.setBackground(new java.awt.Color(12, 12, 12));

        HomePageText.setBackground(new java.awt.Color(51, 51, 51));
        HomePageText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HomePageText.setForeground(new java.awt.Color(255, 255, 255));
        HomePageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomePageText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_24px.png"))); // NOI18N
        HomePageText.setText("Home Page");
        HomePageText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePageTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePageTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePageTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(HomePagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        PartitionPanel.setBackground(new java.awt.Color(12, 12, 12));

        PartitionText.setBackground(new java.awt.Color(51, 51, 51));
        PartitionText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PartitionText.setForeground(new java.awt.Color(255, 255, 255));
        PartitionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PartitionText.setText("Number of Jobs by Partitions");
        PartitionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PartitionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PartitionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PartitionTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PartitionPanelLayout = new javax.swing.GroupLayout(PartitionPanel);
        PartitionPanel.setLayout(PartitionPanelLayout);
        PartitionPanelLayout.setHorizontalGroup(
            PartitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PartitionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PartitionText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PartitionPanelLayout.setVerticalGroup(
            PartitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartitionPanelLayout.createSequentialGroup()
                .addComponent(PartitionText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(PartitionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, -1));

        ErrorsPanel.setBackground(new java.awt.Color(12, 12, 12));

        ErrorsText.setBackground(new java.awt.Color(51, 51, 51));
        ErrorsText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ErrorsText.setForeground(new java.awt.Color(255, 255, 255));
        ErrorsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorsText.setText("Number of Errors");
        ErrorsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ErrorsPanelLayout = new javax.swing.GroupLayout(ErrorsPanel);
        ErrorsPanel.setLayout(ErrorsPanelLayout);
        ErrorsPanelLayout.setHorizontalGroup(
            ErrorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErrorsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ErrorsText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ErrorsPanelLayout.setVerticalGroup(
            ErrorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorsPanelLayout.createSequentialGroup()
                .addComponent(ErrorsText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(ErrorsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        TimePanel.setBackground(new java.awt.Color(12, 12, 12));

        TimeText.setBackground(new java.awt.Color(51, 51, 51));
        TimeText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TimeText.setForeground(new java.awt.Color(255, 255, 255));
        TimeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeText.setText("Average Job Execution Time");
        TimeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TimeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TimeTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(TimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, -1));

        InitPrioPanel.setBackground(new java.awt.Color(12, 12, 12));

        InitPrioText.setBackground(new java.awt.Color(51, 51, 51));
        InitPrioText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InitPrioText.setForeground(new java.awt.Color(255, 255, 255));
        InitPrioText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InitPrioText.setText("Initial Priority Distribution");
        InitPrioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout InitPrioPanelLayout = new javax.swing.GroupLayout(InitPrioPanel);
        InitPrioPanel.setLayout(InitPrioPanelLayout);
        InitPrioPanelLayout.setHorizontalGroup(
            InitPrioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InitPrioPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(InitPrioText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        InitPrioPanelLayout.setVerticalGroup(
            InitPrioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InitPrioText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(InitPrioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, -1));

        KillRequestPanel.setBackground(new java.awt.Color(12, 12, 12));

        KillRequestText.setBackground(new java.awt.Color(51, 51, 51));
        KillRequestText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        KillRequestText.setForeground(new java.awt.Color(255, 255, 255));
        KillRequestText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KillRequestText.setText("Number of Kill Request by User");
        KillRequestText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout KillRequestPanelLayout = new javax.swing.GroupLayout(KillRequestPanel);
        KillRequestPanel.setLayout(KillRequestPanelLayout);
        KillRequestPanelLayout.setHorizontalGroup(
            KillRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KillRequestPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(KillRequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        KillRequestPanelLayout.setVerticalGroup(
            KillRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KillRequestPanelLayout.createSequentialGroup()
                .addComponent(KillRequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(KillRequestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, -1));

        DailyReportPanel.setBackground(new java.awt.Color(12, 12, 12));

        DailyReportText.setBackground(new java.awt.Color(51, 51, 51));
        DailyReportText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DailyReportText.setForeground(new java.awt.Color(255, 255, 255));
        DailyReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DailyReportText.setText("Daily Report");
        DailyReportText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DailyReportPanelLayout = new javax.swing.GroupLayout(DailyReportPanel);
        DailyReportPanel.setLayout(DailyReportPanelLayout);
        DailyReportPanelLayout.setHorizontalGroup(
            DailyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DailyReportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DailyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DailyReportPanelLayout.setVerticalGroup(
            DailyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DailyReportPanelLayout.createSequentialGroup()
                .addComponent(DailyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(DailyReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, -1));

        MonthlyReportPanel.setBackground(new java.awt.Color(12, 12, 12));

        MonthlyReportText.setBackground(new java.awt.Color(51, 51, 51));
        MonthlyReportText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        MonthlyReportText.setForeground(new java.awt.Color(255, 255, 255));
        MonthlyReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthlyReportText.setText("Monthly Report");
        MonthlyReportText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MonthlyReportPanelLayout = new javax.swing.GroupLayout(MonthlyReportPanel);
        MonthlyReportPanel.setLayout(MonthlyReportPanelLayout);
        MonthlyReportPanelLayout.setHorizontalGroup(
            MonthlyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonthlyReportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MonthlyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MonthlyReportPanelLayout.setVerticalGroup(
            MonthlyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonthlyReportPanelLayout.createSequentialGroup()
                .addComponent(MonthlyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(MonthlyReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(12, 12, 12));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        SubmissionsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubmissionsText.setForeground(new java.awt.Color(255, 255, 255));
        SubmissionsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubmissionsText.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmissionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmissionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 60));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 12, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Job Submissions");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 30));

        jPanel11.setBackground(new java.awt.Color(12, 12, 12));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        CompletionsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CompletionsText.setForeground(new java.awt.Color(255, 255, 255));
        CompletionsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompletionsText.setText("0");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(12, 12, 12));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Total Job Submissions");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompletionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompletionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(12, 12, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Total Job Completions");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 200, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(12, 12, 12));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Total Successful Job");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 200, 30));

        jPanel12.setBackground(new java.awt.Color(12, 12, 12));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        SuccessfulText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SuccessfulText.setForeground(new java.awt.Color(255, 255, 255));
        SuccessfulText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SuccessfulText.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuccessfulText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuccessfulText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 200, 60));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(12, 12, 12));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Successful Job Rate");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 30));

        jPanel13.setBackground(new java.awt.Color(12, 12, 12));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        SuccessfulRateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SuccessfulRateText.setForeground(new java.awt.Color(255, 255, 255));
        SuccessfulRateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SuccessfulRateText.setText("0");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(12, 12, 12));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Total Job Submissions");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuccessfulRateText, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuccessfulRateText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 660, -1));

        jPanel14.setBackground(new java.awt.Color(12, 12, 12));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        SubmissionRateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubmissionRateText.setForeground(new java.awt.Color(255, 255, 255));
        SubmissionRateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubmissionRateText.setText("0");

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(12, 12, 12));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Total Job Submissions");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmissionRateText, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(SubmissionRateText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 330, 60));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(12, 12, 12));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Average job submission rate (task/day)");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 340, 30));

        jPanel15.setBackground(new java.awt.Color(12, 12, 12));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        CompletionRateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CompletionRateText.setForeground(new java.awt.Color(255, 255, 255));
        CompletionRateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompletionRateText.setText("0");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(12, 12, 12));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Total Job Submissions");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(12, 12, 12));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Total Job Submissions");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompletionRateText, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompletionRateText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(12, 12, 12));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Average job completion rate (task/day)");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartitionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseEntered
        PartitionPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_PartitionTextMouseEntered

    private void PartitionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseExited
        PartitionPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_PartitionTextMouseExited

    private void ErrorsTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseEntered
        ErrorsPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_ErrorsTextMouseEntered

    private void ErrorsTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseExited
        ErrorsPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_ErrorsTextMouseExited

    private void TimeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseEntered
        TimePanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_TimeTextMouseEntered

    private void TimeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseExited
        TimePanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_TimeTextMouseExited

    private void InitPrioTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseEntered
        InitPrioPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_InitPrioTextMouseEntered

    private void InitPrioTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseExited
        InitPrioPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_InitPrioTextMouseExited

    private void DailyReportTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseEntered
        DailyReportPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_DailyReportTextMouseEntered

    private void DailyReportTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseExited
        DailyReportPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_DailyReportTextMouseExited

    private void MonthlyReportTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseEntered
        MonthlyReportPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_MonthlyReportTextMouseEntered

    private void MonthlyReportTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseExited
        MonthlyReportPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_MonthlyReportTextMouseExited

    private void PartitionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseClicked
        PartitionDashboardPC dashboard = new PartitionDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PartitionTextMouseClicked

    private void ErrorsTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseClicked
        ErrorsDashboardPC dashboard = new ErrorsDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ErrorsTextMouseClicked

    private void TimeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseClicked
        AvgExecTimeDashboard dashboard;
        dashboard = new AvgExecTimeDashboard();
        dashboard.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_TimeTextMouseClicked

    private void InitPrioTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseClicked
        InitPrioDashboardPC dashboard = new InitPrioDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InitPrioTextMouseClicked

    private void DailyReportTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseClicked
        DailyReportPromptDate dashboard = new DailyReportPromptDate();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DailyReportTextMouseClicked

    private void MonthlyReportTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseClicked
        MonthlyReportDashboard dashboard = new MonthlyReportDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MonthlyReportTextMouseClicked

    private void KillRequestTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseClicked
        KillRequestDashboard dashboard = new KillRequestDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KillRequestTextMouseClicked

    private void KillRequestTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseEntered
        KillRequestPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_KillRequestTextMouseEntered

    private void KillRequestTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseExited
        KillRequestPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_KillRequestTextMouseExited

    private void HomePageTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageTextMouseClicked
        HomePage dashboard = new HomePage();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomePageTextMouseClicked

    private void HomePageTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageTextMouseEntered
        HomePagePanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_HomePageTextMouseEntered

    private void HomePageTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageTextMouseExited
        HomePagePanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_HomePageTextMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompletionRateText;
    private javax.swing.JLabel CompletionsText;
    private javax.swing.JPanel DailyReportPanel;
    private javax.swing.JLabel DailyReportText;
    private javax.swing.JPanel ErrorsPanel;
    private javax.swing.JLabel ErrorsText;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel HomePageText;
    private javax.swing.JPanel InitPrioPanel;
    private javax.swing.JLabel InitPrioText;
    private javax.swing.JPanel JobCountPanel;
    private javax.swing.JLabel JobCountText;
    private javax.swing.JPanel KillRequestPanel;
    private javax.swing.JLabel KillRequestText;
    private javax.swing.JPanel MonthlyReportPanel;
    private javax.swing.JLabel MonthlyReportText;
    private javax.swing.JPanel PartitionPanel;
    private javax.swing.JLabel PartitionText;
    private javax.swing.JLabel SubmissionRateText;
    private javax.swing.JLabel SubmissionsText;
    private javax.swing.JLabel SuccessfulRateText;
    private javax.swing.JLabel SuccessfulText;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JLabel TimeText;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
