package fopnetbeans;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shawn
 */
public class NPKillRequestPC extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    DefaultTableModel model;
    
    Color mouseEnterColor = new Color(61,72,73);
    Color mouseExitColor = new Color(12,12,12);
    
    public NPKillRequestPC() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTable();
        showPieChart();
        NPKillRequestsText.setText(Integer.toString(KillRequest.nopermissionrequest));
    }
    
    public void setTable() {
        for (int i = 0; i < KillRequest.X_DATA2.length; i++) {
            Object[] obj = {KillRequest.X_DATA2[i], KillRequest.Y_DATA2[i]};
            model = (DefaultTableModel) Table.getModel();
            model.addRow(obj);
        }
    }
    
    public void showPieChart(){
        
        //create dataset
      
        DefaultPieDataset result = new DefaultPieDataset();
        for (int i = 0; i < KillRequest.X_DATA2.length; i++) {
            result.setValue(KillRequest.X_DATA2[i], Integer.parseInt(KillRequest.Y_DATA2[i]));
        }
        
      //create chart
       
       JFreeChart piechart = ChartFactory.createPieChart3D("Kill Request", result, true, true, false);
  
        PiePlot3D piePlot = (PiePlot3D) piechart.getPlot();
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        PieChart.removeAll();
        PieChart.add(barChartPanel, BorderLayout.CENTER);
        PieChart.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        JobCountPanel = new javax.swing.JPanel();
        JobCountText = new javax.swing.JLabel();
        HomePagePanel = new javax.swing.JPanel();
        HomePageText = new javax.swing.JLabel();
        PartitionPanel = new javax.swing.JPanel();
        PartitionText = new javax.swing.JLabel();
        ErrorsPanel = new javax.swing.JPanel();
        ErrorsText = new javax.swing.JLabel();
        TimePanel = new javax.swing.JPanel();
        TimeText = new javax.swing.JLabel();
        InitPrioPanel = new javax.swing.JPanel();
        InitPrioText = new javax.swing.JLabel();
        KillRequestPanel = new javax.swing.JPanel();
        KillRequestText = new javax.swing.JLabel();
        DailyReportPanel = new javax.swing.JPanel();
        DailyReportText = new javax.swing.JLabel();
        MonthlyReportPanel = new javax.swing.JPanel();
        MonthlyReportText = new javax.swing.JLabel();
        WithPermissionPanel = new javax.swing.JPanel();
        WithPermissionText = new javax.swing.JLabel();
        Arrow2 = new javax.swing.JLabel();
        BarChartPanel = new javax.swing.JPanel();
        BarChartText = new javax.swing.JLabel();
        WithPermPieChartPanel = new javax.swing.JPanel();
        WithPermPieChartText = new javax.swing.JLabel();
        Arrow3 = new javax.swing.JLabel();
        Arrow4 = new javax.swing.JLabel();
        WithoutPermissionPanel = new javax.swing.JPanel();
        WithoutPermissionText = new javax.swing.JLabel();
        Arrow5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new rojerusan.RSTableMetro();
        PieChart = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        NPKillRequestsText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dashboard");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        jPanel2.setBackground(new java.awt.Color(12, 12, 12));
        jPanel2.setPreferredSize(new java.awt.Dimension(226, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 3));

        JobCountPanel.setBackground(new java.awt.Color(12, 12, 12));

        JobCountText.setBackground(new java.awt.Color(51, 51, 51));
        JobCountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JobCountText.setForeground(new java.awt.Color(255, 255, 255));
        JobCountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobCountText.setText("Job Count");
        JobCountText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobCountTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobCountTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobCountTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JobCountPanelLayout = new javax.swing.GroupLayout(JobCountPanel);
        JobCountPanel.setLayout(JobCountPanelLayout);
        JobCountPanelLayout.setHorizontalGroup(
            JobCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JobCountPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JobCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JobCountPanelLayout.setVerticalGroup(
            JobCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobCountPanelLayout.createSequentialGroup()
                .addComponent(JobCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(JobCountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        HomePagePanel.setBackground(new java.awt.Color(12, 12, 12));

        HomePageText.setBackground(new java.awt.Color(51, 51, 51));
        HomePageText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HomePageText.setForeground(new java.awt.Color(255, 255, 255));
        HomePageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomePageText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_24px.png"))); // NOI18N
        HomePageText.setText("Home Page");
        HomePageText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePageTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePageTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePageTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addComponent(HomePageText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(HomePagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        PartitionPanel.setBackground(new java.awt.Color(12, 12, 12));

        PartitionText.setBackground(new java.awt.Color(51, 51, 51));
        PartitionText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PartitionText.setForeground(new java.awt.Color(255, 255, 255));
        PartitionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PartitionText.setText("Number of Jobs by Partitions");
        PartitionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PartitionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PartitionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PartitionTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PartitionPanelLayout = new javax.swing.GroupLayout(PartitionPanel);
        PartitionPanel.setLayout(PartitionPanelLayout);
        PartitionPanelLayout.setHorizontalGroup(
            PartitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PartitionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PartitionText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PartitionPanelLayout.setVerticalGroup(
            PartitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartitionPanelLayout.createSequentialGroup()
                .addComponent(PartitionText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(PartitionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, -1));

        ErrorsPanel.setBackground(new java.awt.Color(12, 12, 12));

        ErrorsText.setBackground(new java.awt.Color(51, 51, 51));
        ErrorsText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ErrorsText.setForeground(new java.awt.Color(255, 255, 255));
        ErrorsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorsText.setText("Number of Errors");
        ErrorsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ErrorsTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ErrorsPanelLayout = new javax.swing.GroupLayout(ErrorsPanel);
        ErrorsPanel.setLayout(ErrorsPanelLayout);
        ErrorsPanelLayout.setHorizontalGroup(
            ErrorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErrorsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ErrorsText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ErrorsPanelLayout.setVerticalGroup(
            ErrorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorsPanelLayout.createSequentialGroup()
                .addComponent(ErrorsText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(ErrorsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        TimePanel.setBackground(new java.awt.Color(12, 12, 12));

        TimeText.setBackground(new java.awt.Color(51, 51, 51));
        TimeText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TimeText.setForeground(new java.awt.Color(255, 255, 255));
        TimeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeText.setText("Average Job Execution Time");
        TimeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TimeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TimeTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(TimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, -1));

        InitPrioPanel.setBackground(new java.awt.Color(12, 12, 12));

        InitPrioText.setBackground(new java.awt.Color(51, 51, 51));
        InitPrioText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InitPrioText.setForeground(new java.awt.Color(255, 255, 255));
        InitPrioText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InitPrioText.setText("Initial Priority Distribution");
        InitPrioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InitPrioTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout InitPrioPanelLayout = new javax.swing.GroupLayout(InitPrioPanel);
        InitPrioPanel.setLayout(InitPrioPanelLayout);
        InitPrioPanelLayout.setHorizontalGroup(
            InitPrioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InitPrioPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(InitPrioText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        InitPrioPanelLayout.setVerticalGroup(
            InitPrioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InitPrioText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(InitPrioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, -1));

        KillRequestPanel.setBackground(new java.awt.Color(102, 102, 255));

        KillRequestText.setBackground(new java.awt.Color(51, 51, 51));
        KillRequestText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        KillRequestText.setForeground(new java.awt.Color(255, 255, 255));
        KillRequestText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KillRequestText.setText("Number of Kill Request by User");
        KillRequestText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KillRequestTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout KillRequestPanelLayout = new javax.swing.GroupLayout(KillRequestPanel);
        KillRequestPanel.setLayout(KillRequestPanelLayout);
        KillRequestPanelLayout.setHorizontalGroup(
            KillRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KillRequestPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(KillRequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        KillRequestPanelLayout.setVerticalGroup(
            KillRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KillRequestPanelLayout.createSequentialGroup()
                .addComponent(KillRequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(KillRequestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, -1));

        DailyReportPanel.setBackground(new java.awt.Color(12, 12, 12));

        DailyReportText.setBackground(new java.awt.Color(51, 51, 51));
        DailyReportText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DailyReportText.setForeground(new java.awt.Color(255, 255, 255));
        DailyReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DailyReportText.setText("Daily Report");
        DailyReportText.setPreferredSize(new java.awt.Dimension(86, 40));
        DailyReportText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DailyReportTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DailyReportPanelLayout = new javax.swing.GroupLayout(DailyReportPanel);
        DailyReportPanel.setLayout(DailyReportPanelLayout);
        DailyReportPanelLayout.setHorizontalGroup(
            DailyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DailyReportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DailyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DailyReportPanelLayout.setVerticalGroup(
            DailyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DailyReportText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(DailyReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 240, 40));

        MonthlyReportPanel.setBackground(new java.awt.Color(12, 12, 12));

        MonthlyReportText.setBackground(new java.awt.Color(51, 51, 51));
        MonthlyReportText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        MonthlyReportText.setForeground(new java.awt.Color(255, 255, 255));
        MonthlyReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthlyReportText.setText("Monthly Report");
        MonthlyReportText.setPreferredSize(new java.awt.Dimension(109, 40));
        MonthlyReportText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MonthlyReportTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MonthlyReportPanelLayout = new javax.swing.GroupLayout(MonthlyReportPanel);
        MonthlyReportPanel.setLayout(MonthlyReportPanelLayout);
        MonthlyReportPanelLayout.setHorizontalGroup(
            MonthlyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonthlyReportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MonthlyReportText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MonthlyReportPanelLayout.setVerticalGroup(
            MonthlyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonthlyReportText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(MonthlyReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 240, 40));

        WithPermissionPanel.setBackground(new java.awt.Color(12, 12, 12));

        WithPermissionText.setBackground(new java.awt.Color(51, 51, 51));
        WithPermissionText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        WithPermissionText.setForeground(new java.awt.Color(255, 255, 255));
        WithPermissionText.setText("  With Permission");
        WithPermissionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WithPermissionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WithPermissionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WithPermissionTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout WithPermissionPanelLayout = new javax.swing.GroupLayout(WithPermissionPanel);
        WithPermissionPanel.setLayout(WithPermissionPanelLayout);
        WithPermissionPanelLayout.setHorizontalGroup(
            WithPermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithPermissionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(WithPermissionText, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        WithPermissionPanelLayout.setVerticalGroup(
            WithPermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithPermissionPanelLayout.createSequentialGroup()
                .addComponent(WithPermissionText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(WithPermissionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 40));

        Arrow2.setBackground(new java.awt.Color(51, 51, 51));
        Arrow2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Arrow2.setForeground(new java.awt.Color(255, 255, 255));
        Arrow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arrow2.setText(">");
        jPanel2.add(Arrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 50, 40));

        BarChartPanel.setBackground(new java.awt.Color(12, 12, 12));

        BarChartText.setBackground(new java.awt.Color(51, 51, 51));
        BarChartText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BarChartText.setForeground(new java.awt.Color(255, 255, 255));
        BarChartText.setText("  Bar Chart");
        BarChartText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarChartTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BarChartTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BarChartTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BarChartPanelLayout = new javax.swing.GroupLayout(BarChartPanel);
        BarChartPanel.setLayout(BarChartPanelLayout);
        BarChartPanelLayout.setHorizontalGroup(
            BarChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarChartPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BarChartText, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarChartPanelLayout.setVerticalGroup(
            BarChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarChartPanelLayout.createSequentialGroup()
                .addComponent(BarChartText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(BarChartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 180, 40));

        WithPermPieChartPanel.setBackground(new java.awt.Color(102, 102, 255));

        WithPermPieChartText.setBackground(new java.awt.Color(51, 51, 51));
        WithPermPieChartText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        WithPermPieChartText.setForeground(new java.awt.Color(255, 255, 255));
        WithPermPieChartText.setText("  Pie Chart");

        javax.swing.GroupLayout WithPermPieChartPanelLayout = new javax.swing.GroupLayout(WithPermPieChartPanel);
        WithPermPieChartPanel.setLayout(WithPermPieChartPanelLayout);
        WithPermPieChartPanelLayout.setHorizontalGroup(
            WithPermPieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithPermPieChartPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(WithPermPieChartText, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        WithPermPieChartPanelLayout.setVerticalGroup(
            WithPermPieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithPermPieChartPanelLayout.createSequentialGroup()
                .addComponent(WithPermPieChartText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(WithPermPieChartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 180, -1));

        Arrow3.setBackground(new java.awt.Color(51, 51, 51));
        Arrow3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Arrow3.setForeground(new java.awt.Color(255, 255, 255));
        Arrow3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arrow3.setText(">");
        jPanel2.add(Arrow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 50, 40));

        Arrow4.setBackground(new java.awt.Color(51, 51, 51));
        Arrow4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Arrow4.setForeground(new java.awt.Color(255, 255, 255));
        Arrow4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arrow4.setText("V");
        jPanel2.add(Arrow4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 50, 40));

        WithoutPermissionPanel.setBackground(new java.awt.Color(102, 102, 255));

        WithoutPermissionText.setBackground(new java.awt.Color(51, 51, 51));
        WithoutPermissionText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        WithoutPermissionText.setForeground(new java.awt.Color(255, 255, 255));
        WithoutPermissionText.setText("  Without Permission");

        javax.swing.GroupLayout WithoutPermissionPanelLayout = new javax.swing.GroupLayout(WithoutPermissionPanel);
        WithoutPermissionPanel.setLayout(WithoutPermissionPanelLayout);
        WithoutPermissionPanelLayout.setHorizontalGroup(
            WithoutPermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithoutPermissionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(WithoutPermissionText, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        WithoutPermissionPanelLayout.setVerticalGroup(
            WithoutPermissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WithoutPermissionText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(WithoutPermissionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 180, 40));

        Arrow5.setBackground(new java.awt.Color(51, 51, 51));
        Arrow5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Arrow5.setForeground(new java.awt.Color(255, 255, 255));
        Arrow5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arrow5.setText(">");
        jPanel2.add(Arrow5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 50, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setBackground(new java.awt.Color(12, 12, 12));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Error"
            }
        ));
        Table.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        Table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Table.setColorSelBackgound(new java.awt.Color(102, 102, 255));
        jScrollPane2.setViewportView(Table);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 570));

        PieChart.setBackground(new java.awt.Color(12, 12, 12));
        PieChart.setLayout(new java.awt.BorderLayout());
        jPanel4.add(PieChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 940, 650));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(12, 12, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("No Permission");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 30));

        jPanel7.setBackground(new java.awt.Color(12, 12, 12));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        NPKillRequestsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NPKillRequestsText.setForeground(new java.awt.Color(255, 255, 255));
        NPKillRequestsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NPKillRequestsText.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPKillRequestsText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPKillRequestsText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JobCountTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobCountTextMouseEntered
        JobCountPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_JobCountTextMouseEntered

    private void JobCountTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobCountTextMouseExited
        JobCountPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_JobCountTextMouseExited

    private void PartitionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseEntered
        PartitionPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_PartitionTextMouseEntered

    private void PartitionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseExited
        PartitionPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_PartitionTextMouseExited

    private void ErrorsTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseEntered
        ErrorsPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_ErrorsTextMouseEntered

    private void ErrorsTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseExited
        ErrorsPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_ErrorsTextMouseExited

    private void TimeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseEntered
        TimePanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_TimeTextMouseEntered

    private void TimeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseExited
        TimePanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_TimeTextMouseExited

    private void InitPrioTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseEntered
        InitPrioPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_InitPrioTextMouseEntered

    private void InitPrioTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseExited
        InitPrioPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_InitPrioTextMouseExited

    private void DailyReportTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseEntered
        DailyReportPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_DailyReportTextMouseEntered

    private void DailyReportTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseExited
        DailyReportPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_DailyReportTextMouseExited

    private void MonthlyReportTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseEntered
        MonthlyReportPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_MonthlyReportTextMouseEntered

    private void MonthlyReportTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseExited
        MonthlyReportPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_MonthlyReportTextMouseExited

    private void JobCountTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobCountTextMouseClicked
        JobCountDashboard dashboard = new JobCountDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JobCountTextMouseClicked

    private void PartitionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartitionTextMouseClicked
        PartitionDashboardPC dashboard = new PartitionDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PartitionTextMouseClicked

    private void ErrorsTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorsTextMouseClicked
        ErrorsDashboardPC dashboard = new ErrorsDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ErrorsTextMouseClicked

    private void TimeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeTextMouseClicked
        AvgExecTimeDashboard dashboard;
        dashboard = new AvgExecTimeDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TimeTextMouseClicked

    private void InitPrioTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitPrioTextMouseClicked
        InitPrioDashboardPC dashboard = new InitPrioDashboardPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InitPrioTextMouseClicked

    private void DailyReportTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyReportTextMouseClicked
        DailyReportPromptDate dashboard = new DailyReportPromptDate();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DailyReportTextMouseClicked

    private void MonthlyReportTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthlyReportTextMouseClicked
        MonthlyReportDashboard dashboard = new MonthlyReportDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MonthlyReportTextMouseClicked

    private void KillRequestTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KillRequestTextMouseClicked
        KillRequestDashboard dashboard = new KillRequestDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KillRequestTextMouseClicked

    private void WithPermissionTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithPermissionTextMouseClicked
        KillRequestPC dashboard = new KillRequestPC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WithPermissionTextMouseClicked

    private void WithPermissionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithPermissionTextMouseEntered
        WithPermissionPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_WithPermissionTextMouseEntered

    private void WithPermissionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithPermissionTextMouseExited
        WithPermissionPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_WithPermissionTextMouseExited

    private void BarChartTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarChartTextMouseClicked
        NPKillRequestBC dashboard = new NPKillRequestBC();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BarChartTextMouseClicked

    private void BarChartTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarChartTextMouseExited
        BarChartPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_BarChartTextMouseExited

    private void BarChartTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarChartTextMouseEntered
        BarChartPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_BarChartTextMouseEntered

    private void HomePageTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageTextMouseClicked
        HomePage dashboard = new HomePage();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomePageTextMouseClicked

    private void HomePageTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageTextMouseEntered
        HomePagePanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_HomePageTextMouseEntered

    private void HomePageTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageTextMouseExited
        HomePagePanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_HomePageTextMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arrow2;
    private javax.swing.JLabel Arrow3;
    private javax.swing.JLabel Arrow4;
    private javax.swing.JLabel Arrow5;
    private javax.swing.JPanel BarChartPanel;
    private javax.swing.JLabel BarChartText;
    private javax.swing.JPanel DailyReportPanel;
    private javax.swing.JLabel DailyReportText;
    private javax.swing.JPanel ErrorsPanel;
    private javax.swing.JLabel ErrorsText;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel HomePageText;
    private javax.swing.JPanel InitPrioPanel;
    private javax.swing.JLabel InitPrioText;
    private javax.swing.JPanel JobCountPanel;
    private javax.swing.JLabel JobCountText;
    private javax.swing.JPanel KillRequestPanel;
    private javax.swing.JLabel KillRequestText;
    private javax.swing.JPanel MonthlyReportPanel;
    private javax.swing.JLabel MonthlyReportText;
    private javax.swing.JLabel NPKillRequestsText;
    private javax.swing.JPanel PartitionPanel;
    private javax.swing.JLabel PartitionText;
    private javax.swing.JPanel PieChart;
    private rojerusan.RSTableMetro Table;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JLabel TimeText;
    private javax.swing.JPanel WithPermPieChartPanel;
    private javax.swing.JLabel WithPermPieChartText;
    private javax.swing.JPanel WithPermissionPanel;
    private javax.swing.JLabel WithPermissionText;
    private javax.swing.JPanel WithoutPermissionPanel;
    private javax.swing.JLabel WithoutPermissionText;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
