package fopnetbeans;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shawn
 */
public class SelectionMenu extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    public static boolean _default = false;
    
    DefaultTableModel model;
    
    public SelectionMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        ThroughoutTheFile = new rojerusan.RSMaterialButtonCircle();
        PromptDate = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ThroughoutTheFile.setText("Throughout The File");
        ThroughoutTheFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThroughoutTheFileActionPerformed(evt);
            }
        });
        jPanel4.add(ThroughoutTheFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 60));

        PromptDate.setText("PROMPT DATE");
        PromptDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromptDateActionPerformed(evt);
            }
        });
        jPanel4.add(PromptDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThroughoutTheFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThroughoutTheFileActionPerformed
        _default = true;
        Errors.Errors(Main.line);
        KillRequest.KillRequest(Main.line);
        JobsByPartitions.JobsByPartitions(Main.line);
        findInitPrio.findInitPrio(Main.line);
        MonthlyReport.MonthlyReport(Main.line);
        SuccessRate.SuccessRate(Main.line);
        try {
            FileProperties.FileProperties(Main.line);
            
        } catch (ParseException ex) {
            Logger.getLogger(PromptDate.class.getName()).log(Level.SEVERE, null, ex);
        }
        HomePage dashboard = new HomePage();
        dashboard.setVisible(true);
        this.dispose();
        try {
            AvgExecTime.AvgExecTime(Main.line);
        } catch (ParseException ex) {
            Logger.getLogger(PromptDate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ThroughoutTheFileActionPerformed

    private void PromptDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromptDateActionPerformed
        PromptDate dashboard = new PromptDate();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PromptDateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle PromptDate;
    private rojerusan.RSMaterialButtonCircle ThroughoutTheFile;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
